CREATE TABLE Users (
    UserID NUMBER PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL,
    Email VARCHAR2(100) UNIQUE NOT NULL,
    Password VARCHAR2(100) NOT NULL,
    Phone VARCHAR2(20),
    Role VARCHAR2(20) CHECK (Role IN ('Admin', 'Organizer', 'Audience'))
);

CREATE SEQUENCE seq_user_id START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE OR REPLACE TRIGGER trg_user_id
BEFORE INSERT ON Users
FOR EACH ROW
BEGIN
    SELECT seq_user_id.NEXTVAL INTO :NEW.UserID FROM dual;
END;
